name: zunote
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
    sdk: ">=2.18.2 <3.0.0"

dependencies:
    cupertino_icons: ^1.0.2
    flutter:
        sdk: flutter
    flutter_riverpod: ^2.0.2
    flutter_svg: ^1.1.5
    simple_shadow: ^0.3.0
    sizer: ^2.0.15

dev_dependencies:
    flutter_lints: ^2.0.0
    flutter_test:
        sdk: flutter

flutter:
    uses-material-design: true

    assets:
        - assets/icons/

    fonts:
        - family: NotoSans
          fonts:
              - asset: assets/fonts/NotoSans-Light.ttf
                weight: 300
              - asset: assets/fonts/NotoSans-Regular.ttf
                weight: 400
              - asset: assets/fonts/NotoSans-Medium.ttf
                weight: 500
              - asset: assets/fonts/NotoSans-SemiBold.ttf
                weight: 600
              - asset: assets/fonts/NotoSans-Bold.ttf
                weight: 700

    # fonts:
    #   - family: Schyler
    #     fonts:
    #       - asset: fonts/Schyler-Regular.ttf
    #       - asset: fonts/Schyler-Italic.ttf
    #         style: italic
    #   - family: Trajan Pro
    #     fonts:
    #       - asset: fonts/TrajanPro.ttf
    #       - asset: fonts/TrajanPro_Bold.ttf
    #         weight: 700
    #
    # For details regarding fonts from package dependencies,
    # see https://flutter.dev/custom-fonts/#from-packages
