name: zunote
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
    sdk: ">=2.18.2 <3.0.0"

dependencies:
    cupertino_icons: ^1.0.2
    easy_localization: ^3.0.1
    flutter:
        sdk: flutter
    flutter_riverpod: ^2.0.2
    flutter_svg: ^1.1.5
    shared_preferences: ^2.0.15
    simple_shadow: ^0.3.0
    sizer: ^2.0.15

dev_dependencies:
    flutter_lints: ^2.0.0
    flutter_test:
        sdk: flutter

flutter:
    uses-material-design: true

    assets:
        - assets/icons/
        - assets/translations/

    fonts:
        - family: NotoSans
          fonts:
              - asset: assets/fonts/NotoSans-Light.ttf
                weight: 300
              - asset: assets/fonts/NotoSans-Regular.ttf
                weight: 400
              - asset: assets/fonts/NotoSans-Medium.ttf
                weight: 500
              - asset: assets/fonts/NotoSans-SemiBold.ttf
                weight: 600
              - asset: assets/fonts/NotoSans-Bold.ttf
                weight: 700
